version: "3.7"

networks:
  app-network:
    driver: bridge

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - app1
      - app2
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  app1:
    image: sbtdn:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - app-network

  app2:
    image: sbtdn:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - app-network